## Interior point method

In [1]:
import numpy as np
import pandas as pd
import copy as copy
import scipy
import scipy.io
import time
import os
from scipy.linalg import solve, LinAlgWarning
import warnings
import matplotlib.pyplot as plt
import matplotlib.ticker as mtick

from matplotlib.animation import FuncAnimation, PillowWriter
import openpyxl
import xlsxwriter

from IPM_functions import (
    create_result_dataframes,
    update_result_dataframes,
    paso_intpoint,
    solve_catch_error,
    update_active_set_mask,
    active_set_diagnostics,
    progress_summary_df_clean,
    build_reduced_system,
    load_lp_problem,
    export_latex_tables,
    export_summary_to_latex
)

#from inpoint_methods import intpoint, intpointR, #,intpointR_mask

pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
pd.set_option('display.max_colwidth', None)

Matplotlib is building the font cache; this may take a moment.
/Users/fattybaking/Documents/thesis_int_point/IPM_functions.py:368: SyntaxWarning: "\%" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\%"? A raw string is also an option.
  .astype(str) + "\%"
/Users/fattybaking/Documents/thesis_int_point/IPM_functions.py:376: SyntaxWarning: "\%" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\%"? A raw string is also an option.
  .astype(str) + "\%"

# Método de puntos interiores con heurística (¿?)

In [ ]:
# Choose a file
#mat_file = 'lp_kb2.mat'     # b = 0
#mat_file = 'lp_afiro.mat'   # bmax = 500, and no mu tends to zero  and no condition problem
#mat_file = 'lp_blend.mat'    # bmax = 26.32, and no mu tends to zero.
#mat_file = 'lp_fit1d.mat'   # b = 0
mat_file = 'lp_fit1p.mat'   # bmax = 216, and no mu tends to zero, condition 10^12
#mat_file = 'lp_kb2.mat'   # bmax = 216, and no mu tends to zero, condition 10^12
#mat_file = 'lp_grow15.mat'  # b = 0, condition 10^6
#mat_file = 'lp_grow22.mat'  # b = 0, condition 1.4e7
#mat_file = 'lp_grow7.mat'   # b = 0, condition 1.2e7

# Load problem
Q, c, A, b, F, d, H = load_lp_problem(mat_file)
AT = A.T
FT = F.T

k = 0
n = Q.shape[0]
m = A.shape[0]
p = F.shape[0]

# Initial values
x = np.ones(n)
lamda = np.zeros(m)
mu = np.ones(p)
z = np.ones(p)
#z = F @ x - d + (0.5)*np.ones(p)

problem_info = {
    "problem_name": mat_file,
    "norm_inf_b": np.linalg.norm(b, np.inf),
    "dim_b": len(b),
    "num_zeros_b": np.sum(b==0),
    "dim_x": n,
    "dim_eq": m,
    "dim_ineq": p
}

tol = 1e-6
kmax = 100

sigma = 0.5 # Valor fijo
tau = sigma * np.dot(mu, z) / p

obj_function_df_value = 0.5 * x @ Q @ x + c @ x
max_complementarity_value = np.max(mu * z)

#Define and initialise the dataframes that will be used to record the results on every iteration for mu, z, tau, the maximum complementarity value: max(mu_i * z_i), and the objective value
mu_df, z_df, tau_df, obj_function_df, max_complementarity_df, active_set_history = create_result_dataframes(p)
mu_df, z_df, tau_df, obj_function_df, max_complementarity_df, active_set_history = update_result_dataframes(k, mu, z, tau, obj_function_df_value, max_complementarity_value, p, mu_df, z_df, tau_df, obj_function_df, max_complementarity_df, active_set_history)

regression_df = pd.DataFrame(columns=active_set_history.columns) #Store any regressed indexes for mu

r_x = Q @ x + AT @ lamda - FT @ mu + c
r_lamda = A @ x - b
r_mu = -F @ x + d + z
r_z = np.multiply(mu, z)

# ld1 is the right-hand side of the complete system with the residuals(but we use the reduces system to solve)
ld1 = np.concatenate((r_x, r_lamda, r_mu, r_z), 0)
norma_cnpo = np.linalg.norm(ld1,np.inf) # this is the CNPO (Condiciones necesarias de primer orden) without the perturbation

red_mu = []

trigger_for_reduced_loop = False
trigger_reason = None

while norma_cnpo > tol and k < kmax:
    # Update diagonal matrices Z and U inside the loop
    Z = np.diag(z)
    U = np.diag(mu)

    ### KKT Matrix (we don't actually use this for calculations as we're using the reduced system).
    # Initial residuals
    row1 = np.hstack((Q, AT, -FT, np.zeros((n, p))))
    row2 = np.hstack((A, np.zeros((m, m + p + p))))
    row3 = np.hstack((-F, np.zeros((p, m + p)), np.identity(p)))
    row4 = np.hstack((np.zeros((p, n + m)), Z, U))

    M = np.vstack((row1, row2, row3, row4))

    # Build the reduced system we will use for calculating
    D = np.diag(mu / z)
    G = Q+FT@D@F
    w = F @ x - d - (tau / mu)
        
    dg = Q @ x + AT @ lamda - FT@mu + c + FT@D@w
    
    # Define K as a block matrix
    m = A.shape[0]
    K = np.block([
        [G, AT],
        [A, np.zeros((m, m))]
    ])
    
    # Calculate the condition number of G
    condG = np.linalg.cond(G,1)
    
    # Define lado derecho of the system of equations (ld)
    ld = -np.concatenate([dg, A @ x - b])
    #norma_cnpo = np.linalg.norm(ld, np.inf)
    
    # Solve the linear system and catch any ill-conditioning warnings from SciPy
    delta_vector = solve_catch_error(K,ld,k) # Reduced system
    
    # Update the sections of the delta_vector
    delta_x     = delta_vector[0:n]
    delta_lamda = delta_vector[n:n + m]
    delta_mu    = - D @ (F @ delta_x + w)
    delta_z     = - ( (1 / mu) * (z * delta_mu - tau) + z )
    
    ### Step size reduction
    alpha_mu = paso_intpoint(mu, delta_mu)
    alpha_z  = paso_intpoint(z, delta_z)
    alpha    = min(alpha_mu, alpha_z)
    #alpha    = 0.995 * min(alpha_mu, alpha_z) # From Javi's thesis
    #print("alpha= " , alpha)
    
    # Percentage changes before we udpate mu and z
    mu_percentage_change = delta_mu/mu
    z_percentage_change  = delta_z/z
    
    # Update variables
    x += alpha * delta_x
    mu += alpha * delta_mu
    lamda += alpha * delta_lamda
    z += alpha * delta_z
    
    # Update tau and residuals
    tau = sigma * np.dot(mu, z) / (p)
    k += 1

    # Recalculate the objective function value and maximum complementarity value for this iteration
    obj_function_value = 0.5 * x @ Q @ x + c @ x
    max_complementarity_value = np.max(mu * z)

    #Update the dataframes that record the values for each iteration
    mu_df, z_df, tau_df, obj_function_df, max_complementarity_df, active_set_history = update_result_dataframes(k, mu, z, tau,
                             obj_function_value, max_complementarity_value, p,
                             mu_df, z_df, tau_df,
                             obj_function_df, max_complementarity_df,
                             active_set_history)

    # Review if mu and z have been meeting the criteria we want (for the last 3 iterations) in order to
    # eliminate them when we start our experiment.
    active_set_history = update_active_set_mask(mu, z, Q, k, tau, active_set_history, mu_df, mu_percentage_change, z_percentage_change)

    # Recalculate residuals
    r_x = Q @ x + AT @ lamda - FT @ mu + c
    r_lamda = A @ x - b
    r_mu = -F @ x + d + z
    r_z = np.multiply(mu, z)  # Element-wise product
    
    ld1 = np.concatenate((r_x, r_lamda, r_mu, r_z), 0)
    norma_cnpo = np.linalg.norm(ld1,np.inf)

    # We save these values again because we're saving them separately so we can update the original variables once we run the heuristic/experiment
    # This allows us to save relevant values of the regular IPM method.
    
    cnpo_norm = norma_cnpo
    primal_residual_norm   = np.linalg.norm(r_lamda, np.inf)
    inequality_residual_norm   = np.linalg.norm(r_mu, np.inf)
    max_complementarity   = np.max(r_z)
    barrier_parameter   = tau
    cond_G  = condG
    objective_value   =  0.5 * x @ Q @ x + c @ x

    #print("\niter=", k, "\t", "||cnpo||=", norma_cnpo)
    #print("Condition number of G:", np.linalg.cond(G,1))
    #print("rcond(G)", (1/np.linalg.cond(G,1)))
    #print("tau =",tau)
    #print(z)
    #print(mu)
    
    #------ This sections is used for reference, but not used for any calculations -------#

    #------ This checks how many of if all components of the complementarity are below a set tolerance (Courtesy of Andreas), and if indices are a subset of the previous indices

    # Create a boolean mask that checks if all components of the complementarity are below a set tolerance
    mask = mu*z <= 1e-5
    
    #print('cuantos chicos mu*z = %g, vector\n' % (sum(mask)), (mu*z)[mask])
    
    #If all values of mu*z are below the tolerance, we check if the indices that fulfil this are a subset of the previous indices that fulfilled this
    if all(mask): #Return True only if EVERY entry in mask is True
        # Once the mu and z have gotten sufficiently small,

        #neg_mu_mask = (-0.52 < mu_percentage_change) & (mu_percentage_change < -0.48)
        #const_z_mask = (-0.01 < z_percentage_change) & (z_percentage_change < 0.01)
        grow_z_mask = (z_percentage_change > -0.03) #& (z_percentage_change < 0.01)
        neg_mu = np.arange( len(mask) )[grow_z_mask]
        
        active_set_history = update_active_set_mask(mu, z, Q, k, tau, active_set_history, mu_df, mu_percentage_change, z_percentage_change)
        
        #print('mus chicos: vector\n', mu[neg_mu])
        if set(red_mu).issubset( neg_mu ):
            print ('IS subset: GOOD')
        else:
            print ('FAILS subset condition: BAD')
            
        #print('mus chicos: vector\n', neg_mu)
        #print('  change in percentages for mu \n', mu_percentage_change[neg_mu] )
        #print('zs tending to positive contants\n', z[neg_mu] )
        #print('  Largest and smallest change for percentages in entries of z  \n', min(z_percentage_change[neg_mu]), max(z_percentage_change[neg_mu] ))
        red_mu = neg_mu.copy()

    if np.all(mu * z < 1e-5):
        trigger_for_reduced_loop = True
        trigger_reason = "complementarity tolerance"
        print("Trigger: complementarity tolerance reached")
        break

    if condG > 1e15:
        trigger_for_reduced_loop = True
        trigger_reason = "ill-conditioned matrix"
        print("Trigger: ill-conditioned matrix detected")
        break
    
    # So here is when we start getting close to the issues of the matrix, as we already exited the while loop

print("Número de iteraciones hasta el criterio de paro:",k)

if not trigger_for_reduced_loop:
    print("Reduced system not triggered — skipping experiment.")

    problem_results_before_heuristic = {
    "KKT residual (‖r‖∞)": cnpo_norm,
    "Primal residual (‖r_p‖∞)": primal_residual_norm,
    "Inequality residual (‖r_d‖∞)": inequality_residual_norm,
    "Complementarity gap (max μᵢ zᵢ)": max_complementarity,
    "Barrier parameter (τ)": barrier_parameter,
    "Condition number κ(G)": cond_G,
    "Objective value f(x)": objective_value
}

    summary_before = progress_summary_df_clean(problem_results_before_heuristic)

    display(summary_before)

    export_summary_to_latex(summary_before, mat_file, output_dir="progress_summary")

if trigger_for_reduced_loop:
    print(f"Starting heuristic (triggered by {trigger_reason})")
    print(f"Condition number of G: {condG:.6e} ({condG:.6f})")
    print(f"rcond(G): {1/condG:.6e} ({1/condG:.6f})")

    k_heuristic = 0
    #tol_red = 1e-10 #check this
    kmax_heuristic = 10
    total_iterations= k + k_heuristic
    frozen_indices_mu_i_zero = set()
    stable_active_indices, regressed_indices = active_set_diagnostics(active_set_history,regression_df,p)
    frozen_indices_mu_i_zero.update(stable_active_indices)
    regressed_df = pd.DataFrame(columns=['Iteration', 'regressed_indices'])

    #Build system outside of the loop:
    Z = np.diag(z)
    U = np.diag(mu)

    # ────────── Build full system ──────────
    r1 = np.hstack((Q, AT, -FT @ U))
    r2 = np.hstack((A, np.zeros((m, m + p))))
    r3 = np.hstack((-U @ F, np.zeros((p, m)), -Z @ U))

    M = np.vstack((r1, r2, r3))   # full system
    cond_full = np.linalg.cond(M, 1)  

    #For recording the results with the new mu values once some turn zero
    mu_df0 = pd.DataFrame(columns=range(p))
    cmpdf0 = pd.DataFrame(columns=['cmp'])
    taudf0 = pd.DataFrame(columns=range(p))

    mu0 = mu.copy()
    mu0[stable_active_indices] = 0
    mu_df0.loc[total_iterations] = mu0

    red_results_df = pd.DataFrame(columns=['Función Objetivo', 'max(mu*z)', 'dim(M1)', 'Condición de G (full)', 'Condición de M1 (sistema nuevo)', 'Filas/Columnas eliminadas comparadas al original'])
    red_results_df = red_results_df.astype({
        'dim(M1)': 'int',
        'Filas/Columnas eliminadas comparadas al original': 'int'
    })
    red_results_df.loc[total_iterations] = [obj_function_value, max_complementarity_value, M.shape[0], cond_full, cond_full, len(stable_active_indices)]

    # this set contains the indices that will stay frozen once we determine that the components of mu are zero
    
    while np.linalg.norm(ld1, np.inf) > tol and k_heuristic < kmax_heuristic:
        print("Starting iteration #",total_iterations+1)
        Z = np.diag(z)
        U = np.diag(mu)

        # ────────── Build full system ──────────
        r1 = np.hstack((Q, AT, -FT @ U))
        r2 = np.hstack((A, np.zeros((m, m + p))))
        r3 = np.hstack((-U @ F, np.zeros((p, m)), -Z @ U))

        M = np.vstack((r1, r2, r3))   # full system

        # Build reduced system (as per my notes) which eliminates the ant
        M, M1, U1, ld1 = build_reduced_system(Q, AT, FT, U, A, F, Z, mu, x, lamda, c, b, d, tau, list(frozen_indices_mu_i_zero))

        cond_full = np.linalg.cond(M, 1)    # for full system
        cond_reduced = np.linalg.cond(M1, 1)  # for reduced system

        print("cond(M1, 1-norm):", np.linalg.cond(M1, 1))

        # SOLVE THE NEW SYSTEM AND EXTRACT THE CHANGES (deltas)
        delta_vector1 = scipy.linalg.solve(M1, -ld1)
        delta_x1     = delta_vector1[:n] # should be the same ?
        delta_lamda1 = delta_vector1[n:n + m] # should be the same ?
        Ddelta_mu1    = delta_vector1[n + m:]
        
        delta_mu1 = U1 @ Ddelta_mu1  # Divide each element of delta_mu1 by the corresponding diagonal element of U

        # Here's the vector transformed back into the original size problem
        full_delta_mu = np.zeros_like(mu)
        active_indices = [i for i in range(p) if i not in frozen_indices_mu_i_zero]
        for i, idx in enumerate(active_indices):
            full_delta_mu[idx] = delta_mu1[i]

        # Reconstruct Δz from the 3rd KKT row (primal feasibility)
        # δz = F δx - (Fx - d - z)  == F @ delta_x1 - r_mu  (since r_mu = -F@x + d + z)
        full_delta_z = F @ delta_x1 - (F @ x - d - z)

        # Recompute step sizes for the reduced-step directions **DOUBLE CHECK THIS LATER
        alpha_mu = paso_intpoint(mu, full_delta_mu)   # ensures μ + α·Δμ ≥ (1-τ)μ > 0
        alpha_z  = paso_intpoint(z,  full_delta_z)    # ensures z + α·Δz ≥ (1-τ)z > 0
        alpha    = min(alpha_mu, alpha_z)

        # Compute mu_percentage_change, z_percentage_change for the reduced step
        mu_percentage_change = full_delta_mu / mu
        z_percentage_change  = full_delta_z / z

        # Apply the step with the same step‑size alpha
        x      += alpha * delta_x1
        lamda  += alpha * delta_lamda1
        mu     += alpha * full_delta_mu
        z      += alpha * full_delta_z

        k_heuristic += 1
        total_iterations= k + k_heuristic

        # Update active_set_history after this reduced iteration
        active_set_history = update_active_set_mask(mu, z, Q, total_iterations, tau, active_set_history, mu_df, mu_percentage_change, z_percentage_change)

        # Recompute the highlighted columns for the next reduced iteration and see if any components stopped meeting the criteria, although it was meeting it before
        stable_active_indices, regressed_indices = active_set_diagnostics(active_set_history,regression_df,p)

        frozen_indices_mu_i_zero.update(stable_active_indices)

        mu0 = mu.copy()
        mu0[list(frozen_indices_mu_i_zero)] = 0
        mu_df0.loc[total_iterations] = mu0

        # Refresh τ and bump iteration counter (optional, for bookkeeping)
        tau = sigma * np.dot(mu, z) / p
        tau0 = sigma * np.dot(mu0, z) / p

        # Recompute residuals for diagnostics
        r_x = Q @ x + AT @ lamda - FT @ mu + c
        v10 = Q @ x + AT @ lamda - FT @ mu0 + c     # dual residual
        r_lamda = A @ x - b                             # primal residual
        r_mu = -F @ x + d + z                        # inequality residual
        r_z = mu * z 
        v40 = mu0 * z                               # complementarity product
        ld1 = np.concatenate((r_x, r_lamda, r_mu, r_z))
        ld10 = np.concatenate((v10, r_lamda, r_mu, v40))

        norm_after = np.linalg.norm(ld1, np.inf)
        norm_after0 = np.linalg.norm(ld10, np.inf)

        mu_df.loc[total_iterations] = mu    # dataframe for graphing the central path
        z_df.loc[total_iterations] = z  
        tau_df.loc[total_iterations] = np.full(p, tau)     # dataframe for graphing the central path
        
        obj_function_value = 0.5 * x @ Q @ x + c @ x
        max_complementarity_value = np.max(mu * z)
        cmp_val0 = np.max(mu0 * z)

        obj_function_df.loc[total_iterations] = obj_function_value
        max_complementarity_df.loc[total_iterations] = max_complementarity_value

        cmpdf0.loc[total_iterations] = cmp_val0
        taudf0.loc[total_iterations] = np.full(p, tau0)     # dataframe for graphing the central path

            # --- CHECK IF ALL μ ARE ZERO ---
        if np.all(mu0 == 0):
            print(f"All μ are zero at iteration {total_iterations}, skipping μ updates and ratio calculation")
            print(f"Final iteration reached at k_heuristic={k_heuristic}, all μ are zero.")
            tau0 = 0
            full_delta_mu = np.zeros_like(mu)
            mu_percentage_change = np.zeros_like(mu)
            k_red_final = k_heuristic
            k_heuristic = kmax_heuristic  # forces loop exit after this iteration
            print("Número de iteraciones del segundo loop:", k_red_final)
        else:
            print("Número de iteraciones del segundo loop:", k_heuristic)

        # After the reduced-loop iterations finish, right before computing problem_results_after_heuristic:
        D = np.diag(mu / z)      # updated D for the new mu and z
        D0 = np.diag(mu0 / z)      # updated D with mu0 and z 
        G = Q + FT @ D @ F 
        G0 = Q + FT @ D0 @ F       # updated G
        condG = np.linalg.cond(G, 1)
        condG0 = np.linalg.cond(G0, 1)

        red_results_df.loc[total_iterations] = [obj_function_value,cmp_val0,(M1.shape[0]),cond_full,np.linalg.cond(M1,1),(n+m+p-M1.shape[0])]
        #red_results_df0.loc[total_iterations] = [obj_function_value,cmp_val0,(M1.shape[0]),cond_full,np.linalg.cond(M1,1),(n+m+p-M1.shape[0])]

        # AFTER computing stable_active_indices, regressed_indices in the reduced loop:

        if len(regressed_indices) > 0:
            regressed_df = pd.concat([regressed_df,
                                    pd.DataFrame({'Iteration': [k_heuristic],
                                                    'regressed_indices': [regressed_indices]})],
                                    ignore_index=True)
            print(f"Iteration of reduced loop {k_heuristic}: Regressed columns:", regressed_indices)
        else:
            print(f"Iteration of reduced loop  {k_heuristic}: No regressed columns")


    problem_results_before_heuristic = {
    "KKT residual (‖r‖∞)": cnpo_norm,
    "Primal residual (‖r_p‖∞)": primal_residual_norm,
    "Inequality residual (‖r_d‖∞)": inequality_residual_norm,
    "Complementarity gap (max μᵢ zᵢ)": max_complementarity,
    "Barrier parameter (τ)": barrier_parameter,
    "Condition number κ(G)": cond_G,
    "Objective value f(x)": objective_value
    }
    
    problem_results_after_heuristic = {
        "KKT residual (‖r‖∞)": np.linalg.norm(ld10, np.inf),
        "Primal residual (‖r_p‖∞)": np.linalg.norm(r_lamda, np.inf),
        "Inequality residual (‖r_d‖∞)": np.linalg.norm(r_mu, np.inf),
        "Complementarity gap (max μᵢ zᵢ)": np.max(v40),
        "Barrier parameter (τ)": tau0,
        "Condition number κ(G)": condG0,  # updated condition number
        "Objective value f(x)": obj_function_value
    }


summary_df = progress_summary_df_clean(problem_results_before_heuristic, problem_results_after_heuristic)

display(summary_df)

export_latex_tables(summary_df, red_results_df, mat_file, p)

Loading problem from: lp_fit1p.mat
Norma infinita de b:  216.0
Problem loaded. n=1677, m=627, p=1677
Number of zeros in b: 0 (0.00%)
Warning: Ill-conditioned matrix (rcond=8.01247e-17): result may not be accurate. in iter 69
IS subset: GOOD
Trigger: complementarity tolerance reached
Número de iteraciones hasta el criterio de paro: 70
Starting heuristic (triggered by complementarity tolerance)
Condition number of G: 1.114122e+15 (1114121983931783.000000)
rcond(G): 8.975678e-16 (0.000000)
Consistently highlighted in last 5 iterations: []
How many in percentage of mu's dimension?  0.0 %
Starting iteration # 71
Deleted 0 rows/columns. M1 shape: (3981, 3981)
cond(M1, 1-norm): 31399449647.452297
Consistently highlighted in last 5 iterations: []
How many in percentage of mu's dimension?  0.0 %
Número de iteraciones del segundo loop: 1
Iteration of reduced loop  1: No regressed columns
Starting iteration # 72
Deleted 0 rows/columns. M1 shape: (3981, 3981)
cond(M1, 1-norm): 62735679582.59881
Consistently highlighted in last 5 iterations: []
How many in percentage of mu's dimension?  0.0 %
Número de iteraciones del segundo loop: 2
Iteration of reduced loop  2: No regressed columns
Starting iteration # 73
Deleted 0 rows/columns. M1 shape: (3981, 3981)
cond(M1, 1-norm): 125407789599.65036
Consistently highlighted in last 5 iterations: []
How many in percentage of mu's dimension?  0.0 %
Número de iteraciones del segundo loop: 3
Iteration of reduced loop  3: No regressed columns
Starting iteration # 74
Deleted 0 rows/columns. M1 shape: (3981, 3981)
cond(M1, 1-norm): 250751892213.60538
Consistently highlighted in last 5 iterations: [0, 5, 6, 8, 9, 12, 13, 14, 17, 19, 20, 23, 24, 27, 30, 33, 37, 38, 39, 42, 46, 47, 49, 50, 52, 53, 55, 56, 58, 61, 62, 64, 65, 67, 68, 70, 71, 73, 74, 75, 79, 80, 81, 85, 86, 88, 89, 90, 93, 97, 98, 99, 102, 106, 107, 109, 110, 112, 113, 114, 117, 121, 122, 123, 126, 129, 133, 134, 135, 139, 140, 141, 145, 147, 151, 152, 153, 157, 158, 160, 161, 162, 165, 168, 171, 175, 176, 177, 180, 184, 185, 187, 188, 189, 193, 194, 196, 199, 200, 201, 204, 207, 210, 214, 215, 217, 218, 219, 223, 224, 226, 227, 229, 230, 231, 234, 237, 240, 244, 245, 247, 248, 249, 253, 254, 256, 257, 258, 261, 264, 267, 270, 274, 275, 277, 278, 279, 282, 285, 289, 290, 292, 293, 294, 298, 299, 300, 303, 306, 309, 313, 314, 315, 319, 320, 321, 325, 326, 328, 329, 330, 334, 335, 336, 340, 341, 342, 345, 348, 352, 353, 354, 358, 359, 361, 362, 364, 365, 366, 369, 372, 375, 378, 382, 383, 384, 388, 389, 390, 393, 396, 400, 401, 403, 404, 406, 407, 409, 410, 412, 413, 414, 417, 421, 422, 424, 425, 427, 428, 430, 431, 432, 436, 437, 439, 440, 441, 444, 447, 451, 452, 453, 456, 460, 461, 463, 464, 465, 468, 472, 473, 475, 476, 477, 481, 482, 483, 487, 490, 491, 492, 496, 497, 499, 500, 501, 504, 508, 509, 510, 514, 515, 517, 518, 520, 521, 522, 525, 528, 531, 534, 538, 539, 540, 543, 546, 549, 553, 554, 556, 557, 559, 560, 561, 565, 566, 568, 569, 571, 572, 573, 576, 580, 581, 583, 584, 586, 587, 589, 590, 591, 594, 597, 600, 604, 605, 607, 608, 609, 613, 614, 616, 617, 619, 620, 622, 623, 624, 627, 630, 633, 636, 639, 643, 644, 646, 647, 649, 650, 652, 653, 655, 656, 657, 661, 663, 666, 669, 672, 675, 679, 680, 681, 684, 687, 690, 694, 695, 696, 699, 702, 706, 707, 709, 710, 711, 714, 718, 719, 721, 722, 724, 725, 726, 730, 731, 733, 734, 735, 738, 742, 743, 744, 748, 750, 753, 757, 758, 760, 761, 763, 764, 766, 767, 769, 770, 772, 773, 774, 777, 781, 782, 784, 785, 786, 790, 791, 793, 794, 795, 798, 801, 805, 806, 808, 809, 811, 812, 813, 816, 819, 822, 826, 827, 828, 832, 833, 835, 836, 837, 841, 842, 843, 846, 850, 851, 853, 854, 856, 857, 859, 860, 862, 863, 864, 868, 869, 871, 872, 874, 875, 877, 878, 880, 881, 882, 885, 889, 890, 891, 894, 898, 899, 901, 902, 903, 906, 910, 911, 912, 915, 919, 920, 922, 923, 924, 928, 929, 930, 933, 937, 938, 940, 941, 942, 945, 948, 952, 953, 955, 958, 961, 962, 963, 966, 969, 973, 974, 976, 978, 981, 985, 986, 987, 990, 994, 995, 996, 1000, 1002, 1006, 1007, 1008, 1011, 1015, 1016, 1017, 1020, 1024, 1027, 1028, 1030, 1031, 1033, 1034, 1035, 1038, 1042, 1043, 1044, 1047, 1051, 1052, 1053, 1056, 1060, 1061, 1062, 1066, 1067, 1069, 1072, 1073, 1074, 1077, 1080, 1084, 1085, 1086, 1089, 1092, 1095, 1098, 1101, 1104, 1108, 1109, 1110, 1114, 1115, 1116, 1119, 1122, 1126, 1127, 1129, 1130, 1131, 1134, 1137, 1140, 1144, 1146, 1149, 1153, 1154, 1156, 1157, 1159, 1160, 1161, 1165, 1166, 1168, 1169, 1171, 1172, 1173, 1177, 1178, 1180, 1181, 1183, 1184, 1185, 1189, 1190, 1191, 1194, 1198, 1199, 1201, 1202, 1203, 1206, 1210, 1211, 1213, 1214, 1216, 1217, 1219, 1220, 1222, 1224, 1226, 1228, 1230, 1232, 1234, 1236, 1238, 1240, 1242, 1244, 1246, 1248, 1250, 1252, 1254, 1256, 1258, 1260, 1262, 1264, 1266, 1268, 1270, 1272, 1274, 1276, 1278, 1280, 1282, 1284, 1286, 1288, 1290, 1292, 1294, 1296, 1298, 1300, 1302, 1304, 1306, 1308, 1310, 1312, 1314, 1316, 1318, 1320, 1322, 1324, 1326, 1328, 1330, 1332, 1334, 1336, 1338, 1340, 1342, 1344, 1346, 1348, 1350, 1352, 1354, 1356, 1358, 1360, 1362, 1364, 1366, 1368, 1370, 1372, 1374, 1376, 1378, 1380, 1382, 1384, 1386, 1388, 1390, 1392, 1394, 1396, 1398, 1400, 1402, 1404, 1406, 1408, 1410, 1412, 1414, 1416, 1418, 1420, 1422, 1423, 1426, 1428, 1430, 1432, 1434, 1436, 1438, 1440, 1442, 1444, 1446, 1448, 1450, 1452, 1454, 1456, 1458, 1460, 1462, 1464, 1466, 1468, 1470, 1472, 1474, 1476, 1478, 1479, 1482, 1484, 1486, 1488, 1490, 1492, 1494, 1496, 1498, 1500, 1502, 1504, 1506, 1507, 1510, 1512, 1514, 1516, 1518, 1520, 1522, 1524, 1525, 1528, 1530, 1531, 1534, 1536, 1538, 1540, 1542, 1544, 1546, 1548, 1550, 1552, 1554, 1556, 1558, 1559, 1562, 1564, 1566, 1568, 1570, 1572, 1573, 1576, 1577, 1580, 1581, 1584, 1586, 1588, 1590, 1592, 1594, 1596, 1598, 1600, 1602, 1604, 1606, 1608, 1609, 1611, 1614, 1616, 1617, 1620, 1622, 1624, 1626, 1628, 1630, 1632, 1633, 1636, 1637, 1640, 1641, 1644, 1645, 1647, 1650, 1651, 1654, 1656, 1657, 1659, 1661, 1663, 1665, 1667, 1669, 1671, 1673, 1675]
How many in percentage of mu's dimension?  48.95646988670245 %
Número de iteraciones del segundo loop: 4
Iteration of reduced loop  4: No regressed columns

,Metric,Before,After,Did it decrease?
0,KKT residual (‖r‖∞),9.167518e-06,1.557035e-05,False
1,Primal residual (‖r_p‖∞),2.842171e-14,5.684342e-14,False
2,Inequality residual (‖r_d‖∞),1.421085e-14,2.273737e-13,False
3,Complementarity gap (max μᵢ zᵢ),9.167518e-06,5.436748e-07,True
4,Barrier parameter (τ),4.331742e-06,1.382013e-07,True
5,Condition number κ(G),1.114122e+15,3.564371e+16,False
6,Objective value f(x),1.364230e+05,1.364230e+05,True

In [3]:
mu_df

            0             1          2           3              4     \
0   1.000000e+00      1.000000   1.000000    1.000000       1.000000
1   7.455306e-01      1.008443   1.016297    1.009521       1.008323
2   6.246359e-01      1.014884   1.024566    1.013552       1.014684
3   3.870164e-01      1.031906   1.049773    1.021777       1.031506
4   1.979318e-01      1.059397   1.105428    1.030766       1.058697
5   1.627712e-01      1.073161   1.142002    1.041422       1.072304
6   1.209553e-01      1.098524   1.219769    1.080738       1.097496
7   6.071792e-02      1.160045   1.429888    1.192130       1.158489
8   5.657796e-02      1.170446   1.483941    1.217283       1.168680
9   3.924328e-02      1.220558   1.763508    1.333307       1.217690
10  3.523251e-02      1.245392   1.965077    1.395565       1.241944
11  2.779123e-02      1.304254   2.549684    1.551895       1.299311
12  2.541141e-02      1.335393   3.083496    1.653760       1.329453
13  2.517233e-02      1.339211   3.165372    1.665196       1.333060
14  1.783228e-02      1.459083   5.795742    2.019579       1.445952
15  1.348713e-02      1.607806  14.903077    2.953875       1.581815
16  1.104160e-02      1.768019  20.775493    5.108439       1.722780
17  9.168284e-03      1.971647  26.029013    9.917953       1.894686
18  8.068084e-03      2.168858  28.936693   13.704656       2.052473
19  4.129823e-03      3.182537  39.399886   23.584851       2.819484
20  3.986520e-03      9.198143  39.513672   23.676483       3.187509
21  3.984079e-03     23.291117  39.534160   23.691763       3.194557
22  3.946827e-03    625.836095  40.360041   24.305916       3.299188
23  3.945969e-03    637.960073  40.379478   24.319389       3.301966
24  3.904397e-03   1288.457622  41.530589   25.080472       3.445200
25  3.857536e-03   1946.299584  42.659544   25.870285       3.619175
26  3.746025e-03   3419.463218  45.252610   27.775740       4.069592
27  3.704868e-03   3939.188982  46.217438   28.646273       4.267183
28  3.703402e-03   3961.095726  46.287174   28.727747       4.275756
29  3.680569e-03   4323.910704  47.592670   30.328246       4.416039
30  3.661722e-03   4557.389593  48.021242   30.644089       4.517690
31  3.576308e-03   5607.213784  49.916902   31.938348       4.992109
32  3.508524e-03   6429.455120  51.477805   32.703748       5.426587
33  3.468716e-03   6926.926308  52.595026   32.723224       5.712187
34  3.382477e-03   7924.423425  54.393592   34.212856       6.390987
35  3.311275e-03   8743.772833  55.977427   35.672177       7.056360
36  3.229119e-03   9686.291829  57.864143   37.492115       7.960957
37  3.071617e-03  11437.081466  60.832509   39.912049      10.235743
38  3.009606e-03  12221.648210  61.981761   41.105669      11.810171
39  2.951287e-03  13042.132567  62.261558   41.157481      13.966977
40  2.883992e-03  13927.272697  62.883011   41.245093      17.303146
41  2.636762e-03  16384.867734  67.140310   44.123404      34.995039
42  2.633489e-03  16418.762976  67.171617   44.176543      73.977397
43  2.491040e-03  18732.566192  64.433775   50.596149    9835.999596
44  2.461994e-03  19202.977434  63.866250   51.979573   11802.199100
45  2.380785e-03  20601.223300  61.854322   56.714519   17735.247416
46  2.338496e-03  21257.615449  61.095507   58.549470   20463.531742
47  2.215248e-03  23157.789006  58.907924   63.865426   28351.696447
48  2.089555e-03  25055.376502  56.799669   69.196580   36230.226777
49  1.978760e-03  26713.154026  55.074799   73.777320   43025.626132
50  1.928883e-03  27718.029735  54.559018   76.006052   46317.830309
51  1.712966e-03  32025.468192  52.392929   85.488670   60360.203858
52  1.614595e-03  33788.004790  51.448373   89.375249   66199.098949
53  1.571221e-03  34562.673413  51.023554   90.976066   68913.645246
54  1.429384e-03  36925.474562  49.848816   95.783242   76576.195115
55  1.310488e-03  38762.225180  49.025384   99.371243   82476.875781
56  1.215044e-03  40122.807269  48.349624  102.324625   86928.356752
57  9.164840e-04  44101.783822  46.415678  111.064947   99914.691643
58  8.878712e-04  44409.654466  46.394564  111.739193  100831.871627
59  8.177757e-04  45736.436679  48.142389  114.595178  103558.972177
60  4.339753e-04  48955.448225  46.427467  121.580701  114103.297670
61  2.175198e-04  49261.986143  46.346708  122.217199  115050.245978
62  1.088607e-04  49251.524284  46.325472  122.211021  115057.213316
63  5.446899e-05  49241.555854  46.307749  122.207294  115060.109705
64  2.725114e-05  49235.913425  46.297566  122.205969  115061.800371
65  1.363239e-05  49232.993193  46.292114  122.206060  115062.939718
66  6.818882e-06  49231.503198  46.289196  122.206705  115063.712158
67  3.410479e-06  49230.747537  46.287632  122.207424  115064.221405
68  1.705633e-06  49230.365996  46.286801  122.207998  115064.539394
69  8.529585e-07  49230.174352  46.286368  122.208375  115064.723985
70  4.265256e-07  49230.078501  46.286148  122.208589  115064.823593
71  2.132762e-07  49230.030614  46.286038  122.208702  115064.874727
72  1.066416e-07  49230.006677  46.285982  122.208759  115064.900437
73  5.332171e-08  49229.994709  46.285955  122.208787  115064.913300
74  2.666108e-08  49229.988724  46.285941  122.208801  115064.919732

            5             6            7         8             9     \
0   1.000000e+00  1.000000e+00     1.000000  1.000000  1.000000e+00
1   9.785213e-01  6.648631e-01     1.007360  1.007551  9.728189e-01
2   9.611474e-01  5.195448e-01     1.013086  1.013229  9.506154e-01
3   9.148288e-01  2.559168e-01     1.028132  1.028181  8.908814e-01
4   8.378715e-01  9.835151e-02     1.052326  1.051834  7.940016e-01
5   7.990224e-01  7.885516e-02     1.064377  1.063168  7.496211e-01
6   7.310600e-01  5.863057e-02     1.087433  1.083813  6.820484e-01
7   5.842043e-01  3.039624e-02     1.142401  1.132526  5.368903e-01
8   5.625529e-01  2.876699e-02     1.151005  1.140040  5.169357e-01
9   4.658919e-01  2.190150e-02     1.191880  1.176263  4.277097e-01
10  4.309422e-01  2.006404e-02     1.211257  1.193278  3.971756e-01
11  3.594420e-01  1.657784e-02     1.256427  1.232888  3.344394e-01
12  3.320861e-01  1.539579e-02     1.279097  1.252434  3.097225e-01
13  3.296894e-01  1.527053e-02     1.281621  1.254714  3.065802e-01
14  2.572034e-01  1.140660e-02     1.359923  1.325881  2.081335e-01
15  1.979702e-01  8.950363e-03     1.442070  1.396329  1.473798e-01
16  1.595368e-01  7.502246e-03     1.510429  1.451075  1.140198e-01
17  1.287787e-01  6.349533e-03     1.573918  1.498255  8.966160e-02
18  1.103904e-01  5.648831e-03     1.613651  1.522845  7.598216e-02
19  4.635038e-02  3.066994e-03     1.742027  1.582347  3.005827e-02
20  4.455234e-02  2.960993e-03     1.710474  1.545686  2.895725e-02
21  4.452323e-02  2.959218e-03     1.711137  1.545058  2.893914e-02
22  4.411489e-02  2.932833e-03     1.755691  1.536182  2.867901e-02
23  4.410581e-02  2.932506e-03     1.756422  1.535941  2.867259e-02
24  4.369453e-02  2.928402e-03     1.789921  1.523012  2.835079e-02
25  4.321304e-02  2.920549e-03     1.822806  1.508897  2.798900e-02
26  4.207558e-02  2.903527e-03     1.890561  1.474814  2.713346e-02
27  4.168358e-02  2.893493e-03     1.911637  1.462239  2.684243e-02
28  4.167164e-02  2.893220e-03     1.912595  1.461704  2.683367e-02
29  4.150160e-02  2.889239e-03     1.928137  1.452883  2.670814e-02
30  4.130610e-02  2.885718e-03     1.940554  1.446955  2.657071e-02
31  4.040610e-02  2.870473e-03     1.999161  1.420062  2.594889e-02
32  3.968647e-02  2.859762e-03     2.050689  1.398788  2.550820e-02
33  3.931489e-02  2.855301e-03     2.082227  1.386927  2.531706e-02
34  3.834016e-02  2.837922e-03     2.152953  1.359035  2.475485e-02
35  3.756191e-02  2.822901e-03     2.217296  1.335731  2.430561e-02
36  3.668020e-02  2.804605e-03     2.297970  1.308536  2.379387e-02
37  3.486667e-02  2.760815e-03     2.462118  1.254819  2.271760e-02
38  3.416264e-02  2.737177e-03     2.543212  1.231857  2.225685e-02
39  3.352356e-02  2.715067e-03     2.607311  1.205498  2.180582e-02
40  3.277877e-02  2.691068e-03     2.705485  1.176640  2.127468e-02
41  3.000307e-02  2.593919e-03     3.109664  1.086743  1.933384e-02
42  2.996709e-02  2.592343e-03     3.118486  1.085545  1.930932e-02
43  2.864413e-02  2.529015e-03     3.728742  1.040417  1.841912e-02
44  2.836722e-02  2.513746e-03     3.907540  1.030857  1.822869e-02
45  2.761311e-02  2.465907e-03     4.323636  1.003622  1.767790e-02
46  2.719864e-02  2.443004e-03     4.738695  0.989217  1.740362e-02
47  2.598198e-02  2.374177e-03     6.242675  0.946786  1.660120e-02
48  2.470622e-02  2.298563e-03     9.433360  0.901992  1.576496e-02
49  2.354662e-02  2.226764e-03    18.650076  0.861192  1.501025e-02
50  2.299667e-02  2.190235e-03    71.868111  0.842578  1.465247e-02
51  2.059850e-02  2.027041e-03   304.814676  0.761085  1.309565e-02
52  1.947969e-02  1.942086e-03   398.324592  0.721980  1.237480e-02
53  1.899380e-02  1.902713e-03   442.892624  0.704783  1.205966e-02
54  1.749970e-02  1.770499e-03   568.822295  0.646396  1.099543e-02
55  1.618458e-02  1.651934e-03   668.484953  0.596011  1.009936e-02
56  1.502639e-02  1.551542e-03   741.144384  0.554811  9.378424e-03
57  1.136676e-02  1.224893e-03   953.987445  0.424030  7.106819e-03
58  1.100965e-02  1.189172e-03   972.379535  0.410873  6.885257e-03
59  1.014751e-02  1.100311e-03  1078.832098  0.378175  6.345482e-03
60  5.330133e-03  6.108042e-04  1250.700414  0.201102  3.362381e-03
61  2.634397e-03  2.990089e-04  1268.492912  0.099040  1.673627e-03
62  1.317096e-03  1.492019e-04  1268.050284  0.049491  8.371436e-04
63  6.590165e-04  7.465174e-05  1267.597448  0.024763  4.188775e-04
64  3.297083e-04  3.734831e-05  1267.337465  0.012389  2.095667e-04
65  1.649362e-04  1.868338e-05  1267.199248  0.006198  1.048356e-04
66  8.250060e-05  9.345339e-06  1267.123824  0.003100  5.243842e-05
67  4.126285e-05  4.674081e-06  1267.081847  0.001550  2.622718e-05
68  2.063619e-05  2.337577e-06  1267.058623  0.000775  1.311661e-05
69  1.031981e-05  1.168983e-06  1267.046129  0.000388  6.559399e-06
70  5.160468e-06  5.845547e-07  1267.039640  0.000194  3.280056e-06
71  2.580396e-06  2.922957e-07  1267.036353  0.000097  1.640131e-06
72  1.290241e-06  1.461527e-07  1267.034705  0.000048  8.200927e-07
73  6.451313e-07  7.307757e-08  1267.033881  0.000024  4.100532e-07
74  3.225683e-07  3.653909e-08  1267.033469  0.000012  2.050283e-07

           10             11            12            13            14    \
0      1.000000       1.000000  1.000000e+00  1.000000e+00  1.000000e+00
1      1.014294       1.008311  9.273002e-01  9.827809e-01  9.363226e-01
2      1.025952       1.014662  8.761842e-01  9.662599e-01  8.920486e-01
3      1.057090       1.031475  7.513568e-01  9.177520e-01  7.894338e-01
4      1.110672       1.058693  5.829410e-01  8.279448e-01  6.578242e-01
5      1.143180       1.072312  5.209097e-01  7.874924e-01  6.000343e-01
6      1.221946       1.097443  4.279111e-01  7.297317e-01  4.948059e-01
7      1.446530       1.158286  2.641076e-01  6.033844e-01  3.045848e-01
8      1.524535       1.168467  2.495755e-01  5.821064e-01  2.880603e-01
9      1.945464       1.217457  1.873962e-01  4.874647e-01  2.170881e-01
10     2.344779       1.241743  1.691734e-01  4.496790e-01  1.958614e-01
11     3.781816       1.299210  1.339627e-01  3.736887e-01  1.544720e-01
12     7.442699       1.329482  1.219332e-01  3.451522e-01  1.402324e-01
13    16.953068       1.333287  1.207898e-01  3.421951e-01  1.388728e-01
14   343.517797       1.453079  8.586583e-02  2.511426e-01  9.732004e-02
15   598.346234       1.601360  6.293863e-02  1.858449e-01  7.003171e-02
16   763.215237       1.760741  4.992647e-02  1.459427e-01  5.504958e-02
17   890.693681       1.962746  4.016597e-02  1.157697e-01  4.387541e-02
18   968.028444       2.157689  3.460856e-02  9.815475e-02  3.756141e-02
19  1198.639162       3.160591  1.508704e-02  4.003383e-02  1.584746e-02
20  1201.047682       7.961316  1.453922e-02  3.850994e-02  1.527787e-02
21  1201.124598       8.664466  1.453042e-02  3.848225e-02  1.526855e-02
22  1203.205810      20.087541  1.441019e-02  3.800758e-02  1.513641e-02
23  1203.448983      47.283345  1.440737e-02  3.799787e-02  1.513312e-02
24  1223.636082    2478.306562  1.427514e-02  3.755015e-02  1.496837e-02
25  1244.031394    4934.661008  1.411804e-02  3.707515e-02  1.477874e-02
26  1294.964303   11153.976388  1.373585e-02  3.599799e-02  1.432605e-02
27  1314.129753   13546.165274  1.358959e-02  3.562471e-02  1.416957e-02
28  1315.059175   13710.719185  1.358489e-02  3.563477e-02  1.416218e-02
29  1331.181317   16772.581035  1.351426e-02  3.593419e-02  1.403714e-02
30  1339.449614   17810.248345  1.344928e-02  3.576419e-02  1.396153e-02
31  1376.172622   22393.883837  1.315590e-02  3.497475e-02  1.361860e-02
32  1403.799636   26145.501808  1.292664e-02  3.443036e-02  1.334927e-02
33  1417.421522   28714.731828  1.279121e-02  3.427142e-02  1.319956e-02
34  1455.013875   33120.784424  1.250762e-02  3.337883e-02  1.286969e-02
35  1486.008426   36702.206922  1.228286e-02  3.251321e-02  1.262680e-02
36  1521.598305   40795.143704  1.202806e-02  3.144406e-02  1.236295e-02
37  1586.893863   48492.029488  1.148550e-02  2.990873e-02  1.172536e-02
38  1613.790996   51730.114491  1.127029e-02  2.911992e-02  1.146730e-02
39  1640.268950   54996.133111  1.105900e-02  2.866577e-02  1.119304e-02
40  1666.805899   58296.335799  1.081298e-02  2.818631e-02  1.089160e-02
41  1751.519321   68560.626286  9.915915e-03  2.577308e-02  9.903261e-03
42  1752.517455   68687.340556  9.904274e-03  2.574271e-02  9.890770e-03
43  1789.532736   74535.346347  9.477703e-03  2.478958e-02  9.427166e-03
44  1797.246157   75774.794703  9.384044e-03  2.454213e-02  9.331496e-03
45  1818.522965   79528.111384  9.102325e-03  2.362584e-02  9.067748e-03
46  1829.110390   81209.970325  8.968460e-03  2.332097e-02  8.924771e-03
47  1859.624204   86071.354242  8.576080e-03  2.243414e-02  8.506153e-03
48  1890.054609   90905.957113  8.163619e-03  2.146630e-02  8.069562e-03
49  1916.330166   95043.286978  7.788075e-03  2.055748e-02  7.674618e-03
50  1928.281455   96935.442589  7.604877e-03  2.008821e-02  7.483727e-03
51  1979.256968  104989.704086  6.806213e-03  1.803186e-02  6.655922e-03
52  2001.110803  108352.575650  6.434357e-03  1.705586e-02  6.279245e-03
53  2012.255485  109876.039355  6.269492e-03  1.662199e-02  6.115057e-03
54  2078.175099  116152.438887  5.717417e-03  1.523513e-02  5.570316e-03
55  2126.064489  120811.988701  5.250354e-03  1.406667e-02  5.111558e-03
56  2142.212114  123349.666957  4.876636e-03  1.307785e-02  4.740783e-03
57  2187.973729  130698.342982  3.699799e-03  9.948549e-03  3.577852e-03
58  2191.365959  131202.444509  3.584547e-03  9.631204e-03  3.466023e-03
59  2202.394249  132370.265622  3.300622e-03  8.735186e-03  3.195189e-03
60  2240.838993  138438.360644  1.752651e-03  4.628624e-03  1.690262e-03
61  2244.058709  138944.667569  8.718028e-04  2.288646e-03  8.445237e-04
62  2244.025086  138937.826785  4.360296e-04  1.145296e-03  4.225543e-04
63  2244.003181  138933.109209  2.181698e-04  5.731523e-04  2.114268e-04
64  2243.990128  138930.500814  1.091517e-04  2.867670e-04  1.057768e-04
65  2243.983101  138929.182219  5.460315e-05  1.434592e-04  5.291441e-05
66  2243.979603  138928.575845  2.731235e-05  7.175909e-05  2.646750e-05
67  2243.977949  138928.327705  1.366034e-05  3.589081e-05  1.323774e-05
68  2243.977175  138928.239477  6.831744e-06  1.794963e-05  6.620387e-06
69  2243.976805  138928.212872  3.416441e-06  8.976325e-06  3.310743e-06
70  2243.976622  138928.205661  1.708406e-06  4.488652e-06  1.655551e-06
71  2243.976530  138928.203386  8.542568e-07  2.244467e-06  8.278277e-07
72  2243.976484  138928.202411  4.271426e-07  1.122271e-06  4.139276e-07
73  2243.976461  138928.201934  2.135749e-07  5.611448e-07  2.069673e-07
74  2243.976450  138928.201695  1.067883e-07  2.805748e-07  1.034845e-07

          15         16        17          18        19            20    \
0     1.000000   1.000000  1.000000    1.000000  1.000000  1.000000e+00
1     1.043145   1.022873  0.972831    1.020669  1.023133  9.794723e-01
2     1.081239   1.043075  0.946345    1.043722  1.046368  9.593731e-01
3     1.188430   1.100739  0.879765    1.108750  1.113169  9.098645e-01
4     1.408656   1.224413  0.783585    1.232283  1.236945  8.319761e-01
5     1.587072   1.315132  0.742433    1.314414  1.306760  7.891038e-01
6     2.011463   1.497280  0.689696    1.498708  1.382756  6.997467e-01
7     3.786390   2.079293  0.570704    2.106137  1.585949  5.197017e-01
8     7.920790   2.323770  0.553056    2.453551  1.608341  4.958486e-01
9    32.553826   3.728355  0.473301    4.693712  1.712599  3.915156e-01
10   42.303230   5.412776  0.445870   14.898910  1.685353  3.527045e-01
11   63.353006  10.671265  0.387551   37.424614  1.617385  2.768726e-01
12   72.346018  13.731275  0.362888   46.854510  1.584775  2.509496e-01
13   73.326735  14.093402  0.360343   48.000445  1.585693  2.486213e-01
14  103.695035  25.415331  0.281997   83.895524  1.630729  1.779448e-01
15  128.082897  34.572938  0.216479  112.150146  1.644746  1.300800e-01
16  143.791123  40.546922  0.174501  129.471744  1.642202  1.027937e-01
17  155.276713  45.048123  0.141406  142.690584  1.642832  8.218556e-02
18  160.941039  47.417840  0.121531  149.729167  1.631357  7.055794e-02
19  182.357469  55.414448  0.051577  175.134548  1.529274  2.913065e-02
20  182.581143  55.485338  0.049558  175.402880  1.489484  2.804901e-02
21  182.592673  55.484039  0.049525  175.409989  1.487608  2.803183e-02
22  182.982656  55.397967  0.049047  175.584633  1.426673  2.780311e-02
23  182.993390  55.394558  0.049040  175.597516  1.425250  2.779597e-02
24  183.687498  55.121443  0.048924  176.676115  1.334914  2.738411e-02
25  184.312469  54.930705  0.048790  177.545312  1.274792  2.693154e-02
26  185.777773  54.488037  0.048601  179.536903  1.162620  2.581206e-02
27  186.423288  54.227670  0.048615  180.171978  1.133749  2.536378e-02
28  186.404138  54.142078  0.048620  180.231726  1.135823  2.534282e-02
29  185.861851  52.333232  0.048744  181.375020  1.188826  2.498179e-02
30  186.090370  52.248208  0.048711  181.724779  1.165948  2.479339e-02
31  187.141325  51.970374  0.048526  183.330757  1.047324  2.395050e-02
32  188.117085  51.740905  0.048378  184.891328  0.905056  2.323412e-02
33  189.172810  51.560568  0.048409  186.268495  0.805950  2.273657e-02
34  189.956934  51.236030  0.048095  187.813762  0.643261  2.187842e-02
35  190.540844  50.863711  0.047833  188.983353  0.527943  2.121074e-02
36  191.172823  50.370326  0.047526  190.275829  0.422221  2.046995e-02
37  192.475213  49.936570  0.046795  193.135894  0.327109  1.901288e-02
38  192.654849  49.752197  0.046577  194.786170  0.305895  1.848838e-02
39  193.484350  50.593522  0.046297  195.820006  0.296732  1.798134e-02
40  194.681540  51.267361  0.045828  196.700709  0.293440  1.743945e-02
41  196.698239  50.777361  0.044157  200.224271  0.258582  1.565497e-02
42  196.720029  50.765937  0.044139  200.272756  0.258114  1.563306e-02
43  196.891254  49.324582  0.045183  203.819527  0.224032  1.481085e-02
44  197.038143  48.975022  0.045423  204.547532  0.219774  1.466239e-02
45  197.924972  47.480631  0.045962  206.470890  0.213488  1.432914e-02
46  198.059688  47.056961  0.046293  207.330469  0.205376  1.407330e-02
47  198.470099  45.847459  0.047277  209.694738  0.181856  1.331922e-02
48  198.771948  44.633121  0.048300  212.066126  0.161456  1.254845e-02
49  198.891222  43.610027  0.049212  214.179847  0.146229  1.186761e-02
50  198.848196  43.185088  0.049649  214.983757  0.139179  1.155238e-02
51  198.668343  41.364565  0.051524  218.393907  0.109718  1.019029e-02
52  198.642565  40.578910  0.052326  219.759064  0.098587  9.579203e-03
53  198.428887  40.322462  0.052749  219.914532  0.093064  9.316182e-03